# fly.toml app configuration file generated for mod-2-lab on 2023-09-16T09:50:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mod-2-lab"
primary_region = "mad"

[build]

[env]
  SESSION_SECURE = "true"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ["app"]
